# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_dojo', '0021_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
