# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_dojo', '0023_auto_20180718_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clothing_admin.Batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clothing_dojo.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='ppppppp', max_length=255),
            preserve_default=False,
        ),
    ]
